todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
  path('', views.index, name='index'),
  path('entry/<int:entry_id>/', views.entry, name='entry'),
  path('add/', views.new_entry, name='new_entry'),
  path('complete/<int:entry_id>/', views.done_entry, name='complete')
]

todolist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('todo.urls')),
]

users/urls.py
"""Defines ULR patterns for user"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
  # Include default auth urls
  path('', include('django.contrib.auth.urls')),
  # Registration page
  path('register/', views.register, name='register'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime, timedelta

one_week = datetime.now() + timedelta(days=7)

class Entry(models.Model):
  text = models.TextField()
  date_added = models.DateTimeField(auto_now_add=True)
  due_by = models.DateTimeField(default=one_week)
  is_completed = models.BooleanField(default=False)
  owner = models.ForeignKey(User, on_delete=models.CASCADE)

  class Meta:
    verbose_name_plural = 'entries'

  def __str__(self):
    return f'{self.text}'

users/models.py
from django.db import models

# Create your models here.

todo/views.py
from django.shortcuts import render, redirect
from datetime import datetime

from .models import Entry

def index(request):
  owner = request.user.id
  entries = Entry.objects.filter(owner=owner).order_by('-date_added')
  context = { 'entries': entries }

  return render(request, 'todo/index.html', context)


def entry(request, entry_id):
  entry = Entry.objects.get(id=entry_id)
  context = { 'entry': entry }

  return render(request, 'todo/entry.html', context)


def new_entry(request):
  title = request.POST['title']
  due_by = datetime.strptime(request.POST['due'], '%Y-%m-%d')
  owner = request.user
  Entry.objects.create(text=title, due_by=due_by, owner=owner)

  return redirect('todo:index')


def done_entry(request, entry_id):
  entry = Entry.objects.get(id=entry_id)

  if entry.is_completed == False:
    entry.is_completed = True
  entry.save()

  return redirect('todo:index')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
  """Register a new user"""
  if request.method != 'POST':
    # Display blank registration form
    form = UserCreationForm()
  else:
    # Process completed form
    form = UserCreationForm(data=request.POST)
    
    if form.is_valid():
      new_user = form.save()
      # Log the user in and then redirect to home page
      login(request, new_user)
      return redirect('todo:index')

  # Display a blan or invalid form
  context = {'form': form}
  return render(request, 'registration/register.html', context)

todo/templates/todo/base.html
<p>
  <a href="{% url 'todo:index' %}">ToDo List</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }}
    <a href="{% url 'users:logout' %}">Log out</a>
  {% else %}
    <a href="{% url 'users:register' %}">Register</a> -
    <a href="{% url 'users:login' %}">Log in</a>
  {% endif %}
</p>

{% block content %}{% endblock content %}

todo/templates/todo/entry.html
{% extends 'todo/base.html' %}

{% block content %}
  <h3>{{ entry }}</h3>
{% endblock content %}

todo/templates/todo/index.html
{% extends "todo/base.html" %}

{% block content %}
  <h2>{{ title }}</p>

  {% if user.is_authenticated %}
    <p>Add new entry:</p>

    <form action="{% url 'todo:new_entry' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="title" required>
      <input type="date" name="due">

      <button name="submit">Add entry</button>
    </form>

    <ul>
      {% for entry in entries %}
        <li>
          <form style="display: inline;" method="post" action="{% url 'todo:complete' entry.id %}">
            {% csrf_token %}

            <input
              type="checkbox"
              value="{{entry.id}}"
              onchange="this.form.submit()"
              {% if entry.is_completed %}
                checked
                disabled
              {% endif %}>
          </form>
          <a href="{% url 'todo:entry' entry.id %}">{{entry}} Due by: {{entry.due_by}}</a>
        </li>
      {% empty %}
        <li>No topics have been added yet</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock content %}